### ISSUE TITLE
Optimize referenced data grants and referenced access needs

### ISSUE THREAD

**Issue by elf-pavlik** [solid/data-interoperability-panel#124]
I'm currently implementing Data Grants. I'm noticing possibility to make them a little bit more ergonomic. Looking at current draft we have:

![image](https://user-images.githubusercontent.com/876431/121829480-475fa080-cc88-11eb-838a-4d86ab577da5.png)

I would find it more ergonomic to have

![image](https://user-images.githubusercontent.com/876431/121830529-db326c00-cc8a-11eb-805b-132aaa8d2c7f.png)

or even

![image](https://user-images.githubusercontent.com/876431/121829583-90175980-cc88-11eb-817a-c3ea274c70c8.png)

We remove the indirection between Access Receipt and Referenced Data Grant, which is also a data grant itself. We still preserve relation between Referenced Data Grant and Data Grant it's inheritance depends on.

Thinking further, and keeping #118 in mind, I'm not sure if we really need Referenced Data Grant or we could simply use Data Grant with `InheritedInstances` scope. As discussed in #109 we would define specific shape for this scope (as well as all other scopes). In that case we would get nice and clear:

![image](https://user-images.githubusercontent.com/876431/121830781-74fa1900-cc8b-11eb-9cea-f004be274309.png)

**Comment by justinwb** [comment]
> Thinking further, and keeping #118 in mind, I'm not sure if we really need Referenced Data Grant or we could simply use Data Grant with `InheritedInstances` scope. As discussed in #109 we would define specific shape for this scope (as well as all other scopes). In that case we would get nice and clear:

I think this is the one to shoot for. Requiring the additional type has never felt completely right to me (ironically so since I added it 😑 ).

**Comment by elf-pavlik** [comment]
SGTM Let's put it on agenda for our call tomorrow and we can try to pick some actions to move in that direction. I could update Primer and TS implementation tomorrow in the afternoon. As for the spec we could at lest put inline issue linking here.

**Comment by justinwb** [comment]
Noting for the purposes of the 1.0 milestone the following work to be done:

1. Remove the hasReferenced* properties, and replace children with "inheritsFromGrant" instead
1. Remove all Referenced* classes 
1. Update operations to use inheritsFromGrant instead
1. Update shapes to reflect the change

**Comment by elf-pavlik** [comment]
> Update shapes to reflect the change

I think that should be done as part of #109
