### ISSUE TITLE
Data Grant should include information about who owns the data

### ISSUE THREAD

**Issue by elf-pavlik** [solid/data-interoperability-panel#140]
This is related to #132

Currently copies of Data Grants created for Remote Agent Data Registration (referenced with `interop:satisfiesDataGrant`) do not include information about who owns the data. If Remote Data Grant has scope `AllRemoteFromAgent` all `AllRemote`, one can keep track on who owns the data based on information from Remote Agent Data Registration. In case of `SelectedRemote` one doesn't have access at that level and can't tell who owns the data.

I think Data Grant should include information about who owns the data. Furthermore it might be beneficial that Remote Data Grant with scope `SelectedRemote` only can reference data grants from the same data owner. Also possibly including information directly on Remote Data Grant.

**Comment by justinwb** [comment]
+1 to this. [This issue](https://github.com/solid/specification/issues/266) is relevant to be able to source the ownership data from something maintained at the protocol level, though it could also be stored / sourced separately if necessary.

**Comment by elf-pavlik** [comment]
Relevant issue https://github.com/solid/data-interoperability-panel/issues/80
