### ISSUE TITLE
Define Data Grants as immutable

### ISSUE THREAD

**Issue by elf-pavlik** [solid/data-interoperability-panel#142]
I think there is no reason to edit Data Grants, especially that they should be easy to cache. Each change to access policies for certain agent should result in new Access Grant which can reuse some of old Data Grants (with no change to them) and issue new Data Grants when alteration is needed.

We might want to introduce some explicit mechanism to revoke data grants, such revocation might include information about which data grant is superseding the revoked grant.

**Comment by justinwb** [comment]
> I think there is no reason to edit Data Grants, especially that they should be easy to cache.

+1 - agree

> We might want to introduce some explicit mechanism to revoke data grants, such revocation might include information about which data grant is superseding the revoked grant.

I think we can use the same receipt flow, but with a specific scope that denotes removal of access - e.g. `interop:NoAccess`

**Comment by TallTed** [comment]
**Revised** (or rather, **Revoked+Issued**) Grants will not necessarily go to `interop:NoAccess`, unlike simply **revoked** Grants which _might_ be defined to implicitly return to either default or `interop:NoAccess` (or both, if default is defined to be `interop:NoAccess`).

There certainly should be an ability to explicitly assert a Grant of `interop:NoAccess` (which should perhaps be the default behavior?), whether or not it's replacing a previous Grant, but `interop:NoAccess` should not be a required intervening stage between "old" and "new" Grants when/if revision happens.

**Comment by justinwb** [comment]
> ...but `interop:NoAccess` should not be a required intervening stage between "old" and "new" Grants when/if revision happens.

Agree 100%

**Comment by justinwb** [comment]
Splitting this issue in two - revocation / change workflow is now in #190

**Comment by justinwb** [comment]
Also noting: 

- Immutability will apply to Access Consents, Data Consents, Access Grants, and Data Grants
- As a result of this immutability, there will be no need to have an updatedAt property in these instances
