### ISSUE TITLE
Replace broad Remote Data Grants with broad Data Consent

### ISSUE THREAD

**Issue by elf-pavlik** [solid/data-interoperability-panel#143]
I've been thinking about it a lot and I'm convinced that this will improve design a lot. I'll try to sum it up here and we should discuss it during the next panel meeting.

1. Current *AllRemote*, *AllRemoteFromAgent* and *SelectedRemote(From Agent)* would become Data Consent rather than Remote Data Grant. Main difference that it would not be shared with Grant Subject and would be only used by Authorization Agent of Social Agent owning the data. (this should also address #113 )
2. Remote/Delegated Data Grant would always be equal or narrower to one Source Data Grant and would include explicit reference to that source data grant. Those would be referenced from Access Receipt delivered to Grant Subject.
3. We do not need Remote Data Registration any more since Authorization Agent can directly work with Access Receipt to issue those granular Remote/Delegated Data Grants. Grant Subject can find all the data by following Access Receipt -> Delegated Data Grant -> Source Data Grant.
4. Remote/Delegated Data Grant, being always equal to or narrower than its Source Data Grant, can be used by Applications as a claim in UMA style claims pushing. This would still require addressing #107

**Comment by TallTed** [comment]
Seems to make sense, as far as it goes....

(`borad` typos in issue title are likely to cause confusion over time... Recommend correcting to `broad`, as I believe was originally intended.)

**Comment by elf-pavlik** [comment]
Title corrected, thanks for spotting @TallTed

**Comment by elf-pavlik** [comment]
![image](https://user-images.githubusercontent.com/876431/127168163-9b0af27d-5c0f-4789-8385-7997bf86ef68.png)

**Comment by justinwb** [comment]
Per panel discussion on 7/27/20201 - 👍 to pursuing the approach
