### ISSUE TITLE
Editorial review and adjustment of shapes

### ISSUE THREAD

**Issue by justinwb** [solid/data-interoperability-panel#151]
* [x] #109 
* [x] right justify the targets throughout interop.shex
* [x] Add shex annotations to interop.shex 
* [x] Create union shapes for Data Consents and Data Grants per approach agreed on in review session
* [x] Use labeled constraints for common properties per approach shared by @ericprud in review session

**Comment by elf-pavlik** [comment]
I think for scope-specific shapes, both Data Consent and Data Grant we could try to use https://shex.io/shex-primer/#labeled-constraints to reuse common triple expressions.
