### ISSUE TITLE
Re-evaluate naming and meaning of scopes used in Data Consent and Data Grant

### ISSUE THREAD

**Issue by elf-pavlik** [solid/data-interoperability-panel#155]
For example renaming *AllRemoteFromAgent* -> *AllFromAgent* which would also address #113 We might also define All as everyone's data including case where Requesting Party === Data Owner. Which means we might consider adding convenience of *AllFromOthers* which would exclude that case. The last one to be honest I'm not sure of scenario where one would want to use. It sounds weird to give consent for everyone else data but not mine 🤔

Possibly also: *AllInstances* -> *AllFromRegistration*, or even better *AllFromRegistry* where we would define that:

* Every Data Registry MUST have maximum one Data Registration for given Shape Tree
* Every Storage SHOULD have maximum one Data Registry

I someone has reason to have separate Data Registrations they preferably would be using separate Storages, in most cases that's what they would want to do anyways.

Following it
*  *InheritInstances* -> *InheritedFromRegistration*, or even better *InheritedFromRegistry*
*  *SelectedInstances* -> *SelectedFromRegistration*, or even Better *SelectedFromRegistry*

This way we have 3 levels of consents for given shape tree

* global
* (social) agent 
* registration/registry (/storage if one registry per storage)

We have all/selected for bottom registration/registry level, so mid level only needs all (*AllFromAgent*), to be more granular one just uses bottom level.

Now we should consider inherited scopes for consents. Following the three levels

* *All* -> *InheritedAll*
* *AllFromAgent* -> *InheritedFromAgent*
* *AllFromRegistration* and *SelectedFromRegistration* -> *InheritedFromRegistration*

Defining distinct Inherited scopes match having different shapes for each of them.

**Comment by justinwb** [comment]
Tracking this exchange from #173:

> When we are dealing with applications, and want to capture access to both local and remote data, should we use a combined scope, multiple scopes, or properties and scopes for local vs. remote? In the example below they're jammed together in "AllInstances" but not sure that feels right.

>> Let's use #155 to figure it out, I already captured some thoughts there.

**Comment by elf-pavlik** [comment]
What do you think about what I originally suggested in the issue?

> For example renaming AllRemoteFromAgent -> AllFromAgent which would also address #113 We might also define All as everyone's data including case where Requesting Party === Data Owner. Which means we might consider adding convenience of AllFromOthers which would exclude that case. 

* *All* - includes case where End-user === Data Owner
* *AllFromOthers* - excludes case where End-user === Data Owner

To be honest I don't see clear use case where I would want to authorize access to everyone's data but not mine. Usually I would start with mine using *AllFromAgent*, possibly add few more selected agents and eventually go all the way to *All*.

**Comment by elf-pavlik** [comment]
Once we do this one, we should finally get #109 done, and do the same for Data Consents.

**Comment by justinwb** [comment]
> Once we do this one, we should finally get #109 done, and do the same for Data Consents.

Agree - was thinking the same 👍

**Comment by justinwb** [comment]
Leaving a note to remind us that the [permissioning section in Data Registrations](https://solid.github.io/data-interoperability-panel/specification/#dr-permissions) should be updated to explain how to apply permissions based on the refactored scopes and associated modes.
