### ISSUE TITLE
Create Agent Registry

### ISSUE THREAD

**Issue by justinwb** [solid/data-interoperability-panel#157]
Registry used to store Access Grants for and/or from a given Agent, including Applications. Also means that we will migrate Application Registry into the Agent Registry.

**Comment by elf-pavlik** [comment]
LGTM I would only ask not to use *acmeproject* as name of application. In primer I use ACME as organization which appears as often as Alice. For applications I use *Projectron* and *PerformChart*, we can add any other number of applications but let's avoid calling them anything ACME-ish. Anything that could lead to conflate application with social agent I would consider counterproductive in effort to draw distinction between those two.

**Comment by justinwb** [comment]
> LGTM I would only ask not to use _acmeproject_ as name of application.

✅  Yup no worries there - will shift over to Projectron / Performchart for examples so we have better alignment (and Acme only as org where applicable)

**Comment by elf-pavlik** [comment]
Are you considering addressing #91 at the same time? There will be no more public registries to probe by appending hashes to their IRIs.

**Comment by justinwb** [comment]
> Are you considering addressing #91 at the same time? There will be no more public registries to probe by appending hashes to their IRIs.

Yeah I've actually already removed the agent id hashing approach with the expectation that interaction with the authorization agent will be required. I'm currently thinking about _where_ to document the interaction with the authorization agent. It feels like we should add a section in the spec for authorization agent (as a third agent type) and put it there. Thoughts?

**Comment by elf-pavlik** [comment]
For now you could just start section on Agent Registration with information how registered agent can discover its registration.

**Comment by justinwb** [comment]
> For now you could just start section on Agent Registration with information how registered agent can discover its registration.

👍 I like that - will add an operation in the API document for it.

Let me know if this sounds about right (borrowing from your proposal in #91):

1. Let `AA` be the IRI object value of `interop:hasAuthorizationAgent` in a Social Agent's WebID Profile Document
2. Send an authenticated `HEAD` or `GET` request to `AA`, including an `HTTP Link` header with relation type: `http://www.w3.org/ns/solid/interop#registeredAgent`.
3. Let `AR` be the IRI value of `anchor` in the `HTTP Link` header with relation type `http://www.w3.org/ns/solid/interop#registeredAgent` of the HTTP Response

**Comment by elf-pavlik** [comment]
> 1. Let `AA` be the IRI object value of `interop:hasAuthorizationAgent` in a Social Agent's WebID Profile Document

👍 

> 2. Send an authenticated `HEAD` or `GET` request to `AA`, including an `HTTP Link` header with relation type: `http://www.w3.org/ns/solid/interop#registeredAgent`.

IMO Request doesn't need any `HTTP Link` header. Server would just do 3 for any authenticated request

> 3. Let `AR` be the IRI value of `anchor` in the `HTTP Link` header with relation type `http://www.w3.org/ns/solid/interop#registeredAgent` of the HTTP Response

Since `AR` is the value of the `anchor` we could make it even more precise by mentioning the Agent's WebID is the target of that link:

3. Let `AR` be the IRI value of `anchor` in the `HTTP Link` header of the HTTP Response with relation type `http://www.w3.org/ns/solid/interop#registeredAgent`, and authenticated Agent's WebID as link target.
