### ISSUE TITLE
Discovery of supported data models and interfaces

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/data-interoperability-panel#17]
How do we discover:
- what data models a data pod supports?
- what interfaces a data pod supports?

**Comment by kjetilk** [comment]
Stupid Question Alert: What do you mean by "data model" in this context? (When I talk about data model in Solid, I simply talk about RDF)

**Comment by RubenVerborgh** [comment]
I see RDF more as the meta-data model. It's about the concrete vocabularies and shapes being used.

**Comment by kjetilk** [comment]
Right, I understand, but I think Model has too many meanings, it can easily become too nebulous to be practical.
