### ISSUE TITLE
Refactor API and Operations

### ISSUE THREAD

**Issue by justinwb** [solid/data-interoperability-panel#179]
It will be most efficient to do one full pass on the API and Operations after refactoring of authorization (access consents, grants) is completed.

**Comment by justinwb** [comment]
@ericprud @elf-pavlik 

I've now gone through and analyzed the contents of the API and Operations document to determine their relevance and usefulness after the specification refactoring. The good news is that I believe we can now dispose of this document entirely, and replace it with some small additions to the spec document, complemented by the impending Authorization Agent Primer.

Specifically, I believe we can do the following:

1. Remove the API and Operations specification, including all references to the same from the other specification documents.
2. Expand the "Data Authorization" section of the specification with the following
    - Definition of an Authorization Agent. Include how to lookup via Social Agent Profile Document, and how to lookup Application Registration or Social Agent Registration.
    - Summary of the key authorization workflows (not the complete operations)
    - Detail the [application request access flow](https://solid.github.io/data-interoperability-panel/api/#authz-apprequest) using a mermaid diagram. The other flows are only slight variations on this, and we can point out the variations without having to detail them. Do not need to detail the sub-operations (e.g. present an access grant, record grant, etc.). Can instead just link to the relevant sections of the spec.
3. Move the wireframes that detail authorization screens and where data is sourced from into the Authorization Agent Primer. We could probably split this out into its own issue and work on it afterwards.

**Comment by elf-pavlik** [comment]
SGTM tomorrow we could all pick some actions, I could help with 3 and the mermaid sequence diagram.

**Comment by ericprud** [comment]
>    * Detail the [application request access flow](https://solid.github.io/data-interoperability-panel/api/#authz-apprequest) using a mermaid diagram. The other flows are only slight variations on this, and we can point out the variations without having to detail them. Do not need to detail the sub-operations (e.g. present an access grant, record grant, etc.). Can instead just link to the relevant sections of the spec.

I'm a big fan of diagrams but they do have an accessibility cost. (Maybe that's why most Web Platform specs don't use them?) If the source is comprensible, perhaps we can get meet W3C accessibility requirements with a link to the source. (We're also not bound by those requirements; it would be reasonable to start out all diagram-y and later on improve accessibility.)

**Comment by justinwb** [comment]
> If the source is comprensible

Great point @ericprud. I can try annotating each key sequence with a number and providing an explanation of each one below the diagram so the context isn't lost when someone can't see/interpret the visual. Would that work?
