### ISSUE TITLE
Project proposal - Data Discovery

### ISSUE THREAD

**Issue by justinwb** [solid/data-interoperability-panel#2]
Proposing that the panel undertakes a project focused on Data Discovery.

The aim of this effort would be to produce a candidate proposal to the [Solid Specification](https://github.com/solid/specification) that defines a mechanism for a data pod to define how its data is stored and indexed so that a given application can automatically find the data that it needs.

**Comment by RubenVerborgh** [comment]
> candidate proposal to the [Solid Specification](https://github.com/solid/specification) that defines how data is stored and indexed

Maybe a bit more specifically:

a proposal for _a mechanism for a data pod_ to define how its data is stored and indexed.


The former would imply that there is one storage/indexing mechanism, whereas the latter provides the building blocks to define such a mechanism, which can be different for every data pod.

**Comment by justinwb** [comment]
> a proposal for _a mechanism for a data pod_ to define how its data is stored and indexed.

Agree! Edited the original comment to reflect this 👍

**Comment by justinwb** [comment]
This proposal was presented to the panel on 8/13. It received consensus agreement to move forward, and it has been initialized at [solid/data-interoperability-pane/data-discovery](https://github.com/solid/data-interoperability-panel/tree/master/data-discovery). 

Closing this issue now that the proposal has moved to the project phase.
