### ISSUE TITLE
Create Primer for Authorization Agent

### ISSUE THREAD

**Issue by justinwb** [solid/data-interoperability-panel#201]
- [ ] Initialize with narrative outline for primer
- [ ] Tie in snippet examples for narrative outline
- [ ] Move Authorization Agent wireframes from legacy API and Operations document

**Comment by elf-pavlik** [comment]
The first draft is now available at https://solid.github.io/data-interoperability-panel/primer/authorization-agent.html

Let's create specific issues and add them to https://github.com/solid/data-interoperability-panel/projects/2
