### ISSUE TITLE
Move videos to Youtube

### ISSUE THREAD

**Issue by woutermont** [solid/data-interoperability-panel#224]
I believe the video intro's to the interop spec describe a "security by obscurity" mechanism for application registration discovery using hashed client IDs. However, in the current draft, I can no longer find this idea, and discovery seems to happen via a header from the Authorization Agent. 

My first question is therefore to clarify that this is indeed a change, and maybe indicate that the video intro's do no longer contain all the latest information.

Secondly, and more importantly i.m.o., this seems to entail that the Authorization Agent needs some kind of back-end for this mechanism to work. Up till now, I had always seen that agent as a front-end only application. Is this not the case?

**Comment by elf-pavlik** [comment]
> My first question is therefore to clarify that this is indeed a change, and maybe indicate that the video intro's do no longer contain all the latest information.

Videos include some outdated information, probably we should hint that in README

> Secondly, and more importantly i.m.o., this seems to entail that the Authorization Agent needs some kind of back-end for this mechanism to work. Up till now, I had always seen that agent as a front-end only application. Is this not the case?

Actually, Authorization Agent is intended to be a server-side service. Generating access grants from access consents. Subscribing to agent registrations on behalf of the grantee, all that makes more sense to run as server-side service.

**Comment by woutermont** [comment]
Discussed in panel meeting of 2022-01-25: videos's could be moved to YouTube, where bubble comments can be used to annotate specific moments of divergence from newer drafts.

Serverside AA is also totally clear now, thx!

**Comment by elf-pavlik** [comment]
#295 notes

Given many changes to the spec, implementations which we can demo, re-recording the videos might be a better option.

We need to update the README all together
