### ISSUE TITLE
Remote data registrations

### ISSUE THREAD

**Issue by woutermont** [solid/data-interoperability-panel#226]
While neither the specification nor the applicaiton primer mention them anymore, since they have been removed by #175, RemoteDataRegistrations are still present in the latest full primer draft (https://solid.github.io/data-interoperability-panel/primer/). Is this just waiting for the next draft to be published?

**Comment by elf-pavlik** [comment]
https://github.com/solid/data-interoperability-panel#initiatives-in-process

Doesn't like that primer anymore. I'll remove it from the repo all together not to cause confusion!

We are going to have dedicated primers for Applications and Authorization Agents since those two audiences differ a lot.

**Comment by woutermont** [comment]
_Discussed in [panel meeting of 2022-01-25](https://github.com/solid/data-interoperability-panel/blob/main/meetings/2022-01-25.md): videos's could be moved to YouTube, where bubble comments can be used to annotate specific moments of divergence from newer drafts._

**Comment by TallTed** [comment]
> _videos's could be moved to YouTube, where bubble comments can be used to annotate specific moments of divergence from newer drafts._

Such "inline" notations on videos may be a nice idea in the abstract, but I wonder whether dependency on a feature of a third party site is appropriate for this.

**Comment by TallTed** [comment]
> We are going to remove links to the old videos altogether https://github.com/solid/data-interoperability-panel/issues/296 and record new videos https://github.com/solid/data-interoperability-panel/issues/298

I am in favor of new recordings, but I strongly advise against entirely removing the old videos. It is important to be able to review history. Certainly, make it plain that "these n videos were recorded in YYYY–YYYY, and are preserved here for historical perspective" along with "these m videos were recorded in 2023, and reflect current status and plans as of MMM".
