### ISSUE TITLE
Identifying the id of requesting agent

### ISSUE THREAD

**Issue by angelaraya** [solid/data-interoperability-panel#229]
[During the agent registration discovery ](https://solid.github.io/data-interoperability-panel/specification/#agent-registration-discovery)- the provided `Authorization` header only contains the id of the social agent who has ownership of the data, not of the application being used to access this data. Without this information the authorization agent is not able know if the application has an existing registration or not.

**Comment by elf-pavlik** [comment]
In previous Solid-OIDC draft DPoP bound access token would have both *webid* (end-user) and *client_id* the application.
In current versiou of Solid-OIDC draft the DPoP bound ID token still have both claims, this time client being the *azp* https://solid.github.io/solid-oidc/#tokens-id

Either way both end-user and the client (application) are know at request time.

**Comment by elf-pavlik** [comment]
@angelaraya confirmed, during the implementation call yesterday, that this issue can be closed
