### ISSUE TITLE
Possible unnecessary unique URL identifying each user in the Authorization Agent 

### ISSUE THREAD

**Issue by angelaraya** [solid/data-interoperability-panel#230]
In the [registration discovery process](https://solid.github.io/data-interoperability-panel/specification/#agent-registration-discovery) it is indicated that the agent will send a request to the social agent authorization agent via the unique URL found in the social agent profile. This request will be accompanied by an `Authorization` header with a webId claim which can be used to uniquely identify the social agent. This way the endpoint can be generic for any user, e.g.: `https://jarvis.example/probe-registration` instead of `https://alice.jarvis.example`.

**Comment by elf-pavlik** [comment]
WebID made available by Solid-OIDC is denoting the *End-user* not the *Resource Owner*. In terms of agent registrations it will be match against `interop:registeredAgent`. Let's take example where `https://kim.example/#id` denotes the end-user.

If Kim tries to discover agent registration by making request to `https://jarvis.example/probe-registration`, it can happen the multiple resource owners using that authorization agents have agent registration for Kim. In that case Authorization Agent would have no indication whose Agent Registry to check for agent registration for Kim.

I Kim tries to discover agen registration by making request to `https://alice.jarvis.example` only Alice's Agent Registry gets check for agent registration for Kim.

**Comment by elf-pavlik** [comment]
@angelaraya confirmed, during the implementation call yesterday, that this issue can be closed
