### ISSUE TITLE
`interop:hasDataResource` used but not documented

### ISSUE THREAD

**Issue by angelaraya** [solid/data-interoperability-panel#235]
Both [Data Grant](https://solid.github.io/data-interoperability-panel/specification/#data-grant) and [Data Consent](https://solid.github.io/data-interoperability-panel/specification/#data-consent) have a `hasDataResource` but neither the shapes nor the interop vocab have this propery. Is this a yet-to-be property or a left over from previous versions?

**Comment by justinwb** [comment]
Agreement in panel session on 2/15 to remove this

**Comment by justinwb** [comment]
Resolved by #244
