### ISSUE TITLE
Use of dataOwner in scope(All) examples

### ISSUE THREAD

**Issue by justinwb** [solid/data-interoperability-panel#248]
In the spec, in the examples for [Scope: All](https://solid.github.io/data-interoperability-panel/specification/#scope-all) - they include a data owner in the data consents. However, the `All` scope should span both the data Alice owns, and the data that was shared with her (owned by other social agents like Juan or Natasha).

**Comment by elf-pavlik** [comment]
This snippet needs to be corrected, shape doesn't include `dataOwner` for `All` scope https://github.com/solid/data-interoperability-panel/blob/main/proposals/specification/interop.shex#L144-L154

We should automate validation of our snippets against correct shapes 😸
