### ISSUE TITLE
exporting storage content (including metadata)

### ISSUE THREAD

**Issue by elf-pavlik** [solid/data-interoperability-panel#38]
In #32 we specify which link relations gets used for each kind of metadata resource. Some of them use full URIs some of them try to reuse registered by IANA link relations. If we want to be able to export all the content of solid storage, i would need to include all the metadata resources as well as all the links between resources and metadata resources. Full URIs can easily be used as predicates in RDF statements but IANA registered link relations don't have official mapping to URIs https://github.com/mnot/I-D/issues/140

**Comment by ericprud** [comment]
@elf-pavlik, that's an enormous thread. If you recall, can you summarize where it ended up and whether the algorithm in [RFC4287](https://tools.ietf.org/html/rfc4287#section-4.2.7.2) sufficiently defines a URL for rel="notAURL"?

(Also, you owe me a band-aid for the blister on my finger from scrolling through I-D#140.)

**Comment by justinwb** [comment]
@elf-pavlik In the absence of stable link relation URIs - would it be fair to say that for any IANA string definition we're using we create a URI for it in the solid namespace that can be used at a minimum for portability during serialization (if not as outright replacements)?
