### ISSUE TITLE
RDF types for ecosystem registries

### ISSUE THREAD

**Issue by justinwb** [solid/data-interoperability-panel#45]
Pulling [this thread](https://github.com/solid/data-interoperability-panel/pull/42/files#r436643917) out into its own issue. Per [this discussion](https://gitter.im/solid/data-interoperability-panel?at=5ed8e7b0778fad0b13476f9f) we're going to merge the ecosystem proposal into master and iterate on it through subsequent pull requests and issues.

```
<#set>
  a solid-ecosystem:registrySet ;
  solid-ecosystem:registryType solid-ecosystem:ApplicationRegistry ;
```
TLDR;
@RubenVerborgh asked why the registries are not using RDF types
@joshdcollins pointed out that we debated this
@acoburn suggested the following using RDF Types:

```
ecosystem:Registry a rdfs:Class .
ecosystem:ApplicationRegistry a ecosystem:Registry .

<#set> a ecosystem:ApplicationRegistry .
```

**Comment by elf-pavlik** [comment]
> `ecosystem:ApplicationRegistry a ecosystem:Registry .`

@acoburn why not instead define it as a subclass?

`ecosystem:ApplicationRegistry rdfs:subClassOf ecosystem:Registry .`

I think your first two statements do not entail `ecosystem:ApplicationRegistry a rdfs:Class .` but my understanding of RDF reasoning may be failing me here.
Once we introduce statement `<#set> a ecosystem:ApplicationRegistry .` we definitely do get that entailment, but possibly not from just first two statements.

I think we would also want to clarify range of `ecosystem:applicationRegistrySet` which name suggests that we expect some kind of `ecosystem:ApplicationRegistrySet` and not more general `ecosystem:RegistrySet`. @justinwb do you intend to have different types of registries in one set or only one type in one set?

**Comment by acoburn** [comment]
> @acoburn why not instead define it as a subclass?

because I spent exactly 5 seconds thinking about this. You are correct, this should be `rdfs:subClassOf` rather than defining this as an `Individual`.

My main point, though, was that RDF has an entire type system that is already well defined and well established. This proposal should use that rather than inventing its own set of predicates that seem to mirror a type system.

**Comment by justinwb** [comment]
> I think we would also want to clarify range of `ecosystem:applicationRegistrySet` which name suggests that we expect some kind of `ecosystem:ApplicationRegistrySet` and not more general `ecosystem:RegistrySet`. @justinwb do you intend to have different types of registries in one set or only one type in one set?

Only one type of registry in a given set. For example, an application registry set would only contain application registries. Here's [the validation](https://tinyurl.com/y94ttyow) used in the proposal to enforce it.

> My main point, though, was that RDF has an entire type system that is already well defined and well established. This proposal should use that rather than inventing its own set of predicates that seem to mirror a type system.

Completely fair point. As @joshdcollins pointed out we debated this a bit and weren't convinced it was necessary in this case given the similarity of the different types of registries. Going to revisit that decision based on the feedback though 🙂

**Comment by justinwb** [comment]
@acoburn @elf-pavlik @RubenVerborgh A whole bunch of updates in [this merge](https://github.com/solid/data-interoperability-panel/pull/54) that I believe should resolve this issue (though i'm sure we could continue to iterate on the data model in new/successive ones as needed). [Rendered version here](https://solid.github.io/data-interoperability-panel/ecosystem/).
