### ISSUE TITLE
ecosystem: suggest SHA-256 instead of SHA3-256 for app ID hash

### ISSUE THREAD

**Issue by zenomt** [solid/data-interoperability-panel#48]
the Ecosystem proposal describes hashing the app ID with SHA3-256 and using the resulting hex string to find the application entry. i think using a SHA3 ([FIPS PUB 202](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.202.pdf)) hash is an unnecessary hindrance for implementers vs using the more established SHA-256 ([FIPS PUB 180-4](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.180-4.pdf)). i suggest using SHA-256 instead of SHA3-256.

the newness of SHA3 means there are fewer implementations available, and fewer runtime environments ship with it out of the box. for example, OpenSSL prior to version 1.1.1 (the latest version) does not support SHA3 hashes. it may not be available natively in all web browsers and language runtimes. this may require Solid applications and compatible servers to carry around their own implementations rather than leveraging well-established, out-of-the-box libraries or native platform support.

FIPS-180-4 hashes like SHA-256 are sufficiently resistant to collisions, and in this context the hash is only providing a normalization/canonicalization/obfuscation of the app ID. there is no difference between using SHA-256 or SHA3-256 (or even base64url) to prevent an adversary from probing whether a user uses a particular app.

**Comment by elf-pavlik** [comment]
> here is no difference between using SHA-256 or SHA3-256 (or even base64url) to prevent an adversary from probing whether a user uses a particular app.

I've just suggested to rely on client's public key rather than url https://github.com/solid/data-interoperability-panel/issues/49

**Comment by justinwb** [comment]
> FIPS-180-4 hashes like SHA-256 are sufficiently resistant to collisions, and in this context the hash is only providing a normalization/canonicalization/obfuscation of the app ID. there is no difference between using SHA-256 or SHA3-256 (or even base64url) to prevent an adversary from probing whether a user uses a particular app.

Thanks for raising this @zenomt. You're absolutely correct - we just need a good hashing algorithm - nothing specific to SHA3. I'm comfortable with this proposed adjustment. 

(in parallel we'll deliberate on @elf-pavlik's proposed approach with public keys in #49)

**Comment by elf-pavlik** [comment]
If we just need url encoding, why don't just use [RFC 3986 2.1.  Percent-Encoding](https://tools.ietf.org/html/rfc3986#section-2.1)? In browser application could simply use [`encodeURI()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI)

**Comment by zenomt** [comment]
@elf-pavlik a one-way hash still provides an obstacle to detecting what apps a user might be using. if the app ID is encoded in a reversible manner, then you can immediately see what app that is by decoding it. if the app ID is hashed, then hashes of suspected candidates must be tried to see if there's a match.

there's no difference in *probing* for a match, but there is a difference in immediately seeing what app(s) are being used. using a hash is *better* for privacy.

**Comment by justinwb** [comment]
As a follow-up to this, in the most recent round of updates I kept the one-way hash (adjusted to SHA-256 per @zenomt's suggestion in the OP). I have an inline issue that links out here, in a section I added that is dedicated to [Naming application registration resources](https://solid.github.io/data-interoperability-panel/ecosystem/#appreg-naming). Here's some text that was added related to the discussion here:

> There is a reasonable argument for whether or not a one-way hash alogorithm like SHA-256 is appropriate, as we are primarily using it as a mechanism for URL encoding to create uniform, opaque resource names, and the ApplicationID for a given Application is publicly shared. However, the use of one-way hash does add a modicum of additional privacy at a miniscule expense.

**Comment by elf-pavlik** [comment]
The latest spec discovers agent registration via link headers in response to an authenticated request https://solid.github.io/data-interoperability-panel/specification/
