### ISSUE TITLE
[Ecosystem] Rely on client's public key rather than hashed client's url

### ISSUE THREAD

**Issue by elf-pavlik** [solid/data-interoperability-panel#49]
Ecosystem proposal suggest reliance on hashed url of the client ([6.1.2. Finding a specific registered application](https://solid.github.io/data-interoperability-panel/ecosystem/#reg-findapp)). This still allows everyone to probe anyone else's registry for registrations of clients with broadly known urls. Public key used by client instance in DPoP are less known and could be used instead in uri template used for client registration.

*EDIT* even clients running as server side service, could create distinct public key per user and use that key when acting on behalf of that user. This would prevent having one public key across many users. (see also #50)

**Comment by joshdcollins** [comment]
@elf-pavlik A note about the visibility of registration.

In 6.1.2:
> Only the resource controller (Alice) and her trusted agents should have visibility and control of her application registry sets and registries.

As a result a Pod cannot be publicly scanned to determine what applications have been registered.  Only Alice (using any application piloted by her) or agents she trusts completely would be able to read this.

**Comment by elf-pavlik** [comment]
So Alice has to authenticate with a client for it to access any of the registrations. Still it allows any client that Alice authenticates with to access registrations of all the clients which urls it knows of (it just needs to hash them) and use in uri template.

**Comment by justinwb** [comment]
> So Alice has to authenticate with a client for it to access any of the registrations. Still it allows any client that Alice authenticates with to access registrations of all the clients which urls it knows of (it just needs to hash them) and use in uri template.

Without the ability to impose an additional client-constraint on user-piloted applications in an authorization statement (or in a token), this is correct. However, the proposal recommends that application registration entries have an additional client constraint on the authorization rule for [user-piloted applications](https://solid.github.io/data-interoperability-panel/ecosystem/#user-piloted-application). See [Client Identification](https://solid.github.io/data-interoperability-panel/ecosystem/#client).

Consequently, the proposal represents the following behavior:

- Nevernote is a user-piloted application
- Nevernote registers with Alice's pod, with a registration entry at https://alice.pod.example/applications/ec0edcd4f8ac00afed60f9929647f65bc87a2aeedf82e4d02f9d4221d9e5c0ae, using a hash of NeverNote's ApplicationID (https://nevernote.example/id#agent).
- The authorization statement for https://alice.pod.example/applications/ec0edcd4f8ac00afed60f9929647f65bc87a2aeedf82e4d02f9d4221d9e5c0ae says that only Alice + Her [Trusted Agents](https://solid.github.io/data-interoperability-panel/ecosystem/#trusted), or Alice + NeverNote, can access that registration entry.
- For another application to access that application registration entry, it would still need alice to be the authenticated agent, and would have to find a way to impersonate the application identifier in the token to say it is Alice piloting NeverNote, or Alice piloting one of her Trusted Agents.
- We document the [limitations to this kind of client identification](https://solid.github.io/data-interoperability-panel/ecosystem/#client), but in use cases like this where the resource controller is compartmentalizing her own data based on the applications she is using, this compartmentalization is still valuable.

**Comment by elf-pavlik** [comment]
Relying on client's public key has another advantage. User discloses to RS just the minimum information necessary for RS to enforce constraints that user puts on that client. Having just client's public key, RS doesn't even know *redirect_uri* of the client and can't keep track on what specific software applications users are delegating their access to.

**Comment by elf-pavlik** [comment]
We discussed it during the meeting. Current draft focuses on user registering client with their registry.
Also @justinwb further clarify access restrictions on registrations.
