### ISSUE TITLE
Project proposal - Standardize Extended Profile / Preferences

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/data-interoperability-panel#5]
Currently, we use the WebID Profile document as a starting point for Solid apps to determine user settings and preferences (as recommended in the [Data Discovery proposal](https://github.com/solid/solid/blob/master/proposals/data-discovery.md) -- see also issue #2 on this repo)

This brings up a couple of issues, such as:

* [solid-spec #189 - Security/provenance issue with Extended Profile](https://github.com/solid/solid-spec/issues/189) (which discusses implied usage of `sameAs` and `seeAlso` for clients loading the extended profile)
* [solid-spec #128 - Provide guidelines for user profile document ](https://github.com/solid/solid-spec/issues/128) (which asks for guidance about the user preferences mechanism)
* Public vs private settings

In addition to Data Discovery related triples in the WebID Profile, we also have some authentication-related triples (such as the `solid:oidcIssuer` statements).

**Comment by kjetilk** [comment]
I think the key problem I see with this is that when you get to extensions, it seems likely that what people would want in there is very diverse, and so standardizing an extended profile might not be fruitful. 

To me, it seems to have data interop through a broad selection of vocabs is a better approach.

**Comment by justinwb** [comment]
This proposal was presented to the panel on 8/13. It received consensus agreement to move forward, and it has been initialized at [solid/data-interoperability-pane/user-profile](https://github.com/solid/data-interoperability-panel/tree/master/user-profile). 

Closing this issue now that the proposal has moved to the project phase.
