### ISSUE TITLE
shapetree link gives: site can't be reached

### ISSUE THREAD

**Issue by michaud** [solid/data-interoperability-panel#55]
https://solid.github.io/data-interoperability-panel/ecosystem/#biblio-shapetrees

**Comment by justinwb** [comment]
@michaud Thanks for reporting! That site will go live in the next week or two - will update that link to the current github.io page in the interim.

**Comment by justinwb** [comment]
@michaud Have resolved this for the time being with [this commit](https://github.com/solid/data-interoperability-panel/commit/822a4585cb8f35368aa67cc5943024571f0d465e). Will update again once shapetrees.org goes live.
