### ISSUE TITLE
Project Proposal - Data Portability

### ISSUE THREAD

**Issue by justinwb** [solid/data-interoperability-panel#6]
Proposing that the panel undertakes a project focused on Data Portability.

The aim of this effort would be to produce a candidate proposal to the Solid Specification that defines a mechanism for how one migrates their data, including the "meta" information around it (i.e. access control, audit history, shape constraints) from one Solid pod to another, or from one Solid pod to a different medium altogether.

**Comment by kjetilk** [comment]
My main mechanism of data portability would be through domain ownership, which does not need to be covered by a panel. I assume that this is for cases where domain ownership isn't possible?

**Comment by ericprud** [comment]
I assumed that this scope starts after that. You may update the A record from `1.2.3.4` to `1.2.3.5`;
1. how do you migrate your data and meta-data?
2. what do you do with special infrastructure bits are particular to `1.2.3.4`, e.g. ACL extensions which give you more fine-grained control?
3. how do you find out about extensions available on `1.2.3.5`?
4. does the `1.2.3.5` allow you to serve the same media types (javascript, java classes)?

**Comment by justinwb** [comment]
This proposal was presented to the panel on 8/13. It received consensus agreement to move forward, and it has been initialized at [solid/data-interoperability-pane/data-portability](https://github.com/solid/data-interoperability-panel/tree/master/data-portability). 

Closing this issue now that the proposal has moved to the project phase.
