### ISSUE TITLE
Add examples of Data Registries for Projects and Tasks

### ISSUE THREAD

**Issue by elf-pavlik** [solid/data-interoperability-panel#61]
I think we can add some Data Registries for Projects and Tasks. I think `acme.example` would be most interesting one to start with. We have 3 projects there with different people having different kinds of access to them. We also have this requirement: "moving task between projects should not cause URL to change".

How do you see Data Registries applying here? Would `acme.example` only have one registry for Projects and another one for Tasks?
I guess for access control on Tasks we would rely on [Conditional access by relationship](https://solid.github.io/authorization-panel/wac-ucr/#conditional-relationship). Given that [Task shape](https://solid.github.io/data-interoperability-panel/primer/#tasks) mandates use of `ex:inProject` predicate.

**Comment by justinwb** [comment]
There would only be a single registry for acme.example, with project and task each being a registered shape tree in that registry. Registered data Instances for distinct projects and tasks would then get put into that registry under their respective registrations.

**Comment by elf-pavlik** [comment]
As I understand we would have just one Data Registry with two Data Registrations:
* `eco:registeredShapeTree shapes:ProjectShape ;`
* `eco:registeredShapeTree shapes:TaskShape ;`

All the projects would be data instances in the first one and all the tasks would be data instances in the second one.

**Comment by justinwb** [comment]
> All the projects would be data instances in the first one and all the tasks would be data instances in the second one.

Yes exactly!
