### ISSUE TITLE
Data Registration - Data Model - location of container

### ISSUE THREAD

**Issue by joshdcollins** [solid/data-interoperability-panel#72]
Issue created following conversation in December 8th Interop Panel:

With the latest PR for the data registration data model the `hasRegisteredDataInstance` predicate was removed in lieu of relying on `ldp:contains` to determine instances of a data registration.

Suggestion is to add a statement to the `interop:DataRegistration` that describes the location of the container where these instances are physically stored.

1. This restores the ability to 'follow your nose' to instances
2. It allows for a decoupling of the physical location of the data registration and the storage of instances themselves.

**Comment by justinwb** [comment]
> Suggestion is to add a statement to the `interop:DataRegistration` that describes the location of the container where these instances are physically stored.
> 
> 1. This restores the ability to 'follow your nose' to instances
> 2. It allows for a decoupling of the physical location of the data registration and the storage of instances themselves.

This seems reasonable to me ✅   Will make the change soon and leave this open in meantime.

**Comment by elf-pavlik** [comment]
I think we may not need that unless we will not be able to resolve AuthZ issue related to granular access modes on containers.

**Comment by elf-pavlik** [comment]
We are discussing it again in #225 I will close this one in favor of the newer issue.
