### ISSUE TITLE
Data Registration - Data Model - clarify use of interop:registeredType

### ISSUE THREAD

**Issue by joshdcollins** [solid/data-interoperability-panel#74]
Issue created following conversation in December 8th Interop Panel:

Questions / concerns related to purpose of `interop:registeredType` and potential confusion that may create as compared to `interop:hasRegisteredShapeTree`.

Goal is to clarify use of this statement.

**Comment by justinwb** [comment]
Maintaining one or more types in the registration is really meant as an optimization to aid those doing discovery or indexing based on type. What's being registered is the shape tree type, and this is more of an informative add.

**Comment by elf-pavlik** [comment]
I think we should only keep `interop:hasRegisteredShapeTree`. If some implementation showcases need for `interop:registeredType` we can always re-introduce it.

**Comment by elf-pavlik** [comment]
Latest version of vocab and spec doesn't use `interop:registeredType`
