### ISSUE TITLE
Agree on recurring meeting time and frequency

### ISSUE THREAD

**Issue by justinwb** [solid/data-interoperability-panel#8]
We need to agree on both a frequency of meeting (e.g. weekly, bi-weekly), and the time slot we should reserve for it.

For starters, please take a look at [this doodle](https://doodle.com/poll/xf637ehp35gmerpr) and identify time windows that you'd be willing to take 60-90 minutes and talk data interop in solid. Because of how doodle works, I just created a bunch of 30 minute slots. Don't bother checking off anything less than 60 consecutive minutes.

Following that, please comment on this thread about whether you have a preference for weekly or bi-weekly frequency. We've identified a number of projects to undertake, so weekly might be necessary as we get up and running. Still, lets hear opinions on this.

**Comment by RubenVerborgh** [comment]
Thanks @justinwb. Filled it out. I propose bi-weekly for 60 minutes, increase frequency if needed.

**Comment by justinwb** [comment]
Hi everyone,

Based on the results from the [Doodle Poll](https://doodle.com/poll/xf637ehp35gmerpr), these were the top time slots that came back:

- Mondays - 2-3:30 Eastern Time
- Wednesdays - 2-3 Eastern Time

I'd like to propose the Monday slot from 2-3, bi-weekly, starting next week. In the event that we want to meet on off-weeks, we should look at the Monday slot first, and if that doesn't work, the Wednesday slot.

Please use 👍 or 👎 on this comment, or feel free to reply in thread below.

**Comment by RubenVerborgh** [comment]
> these were the top time slots that came back:
> 
>     * Mondays - 2-3:30 Eastern Time
> 
>     * Wednesdays - 2-3 Eastern Time

That doens't seem right; I have them as 3:30–4:30 and 3–4?

**Comment by justinwb** [comment]
> That doens't seem right; I have them as 3:30–4:30 and 3–4?

@RubenVerborgh You're completely right - for some reason Doodle switched to a different time zone on me 👎 

So with proper time-zone adjust, I'd like to suggest:

- Mondays at 3:30-4:30 Eastern, Bi-weekly starting next week

**Comment by justinwb** [comment]
Great - have sent out an invite for this time slot with dial-in details. If you weren't on the invite, it's because I don't have your e-mail address. Feel free to update https://github.com/solid/process/blob/master/panels.md#data-interoperability with it, or just reach out to me directly on gitter to get added to the calendar invite.

Otherwise, you can connect using this link on Mondays at 3:30-4:30 Eastern Time, every other week starting on 8/26:
https://global.gotomeeting.com/join/620786365
