### ISSUE TITLE
Agree on terminology to distinguish software agent from social agent

### ISSUE THREAD

**Issue by elf-pavlik** [solid/data-interoperability-panel#80]
I think we should already settle on some distinct terms for those two different types of agents. To be honest I don't care that much about specific words we pick as long as they have clear definitions and use chosen terms consistently across specifications.

We seem already to call Software Agent as *Application* sometimes more specific *OAuth Client*.
When it comes to Social Agent we seem to miss it all together. I would like to have equivalent of [Legal Person](https://en.wikipedia.org/wiki/Legal_person). 

I'd like to point out that ACP has distinct predicates `acp:agent` and `acp:client`. In Solid-OIDC we also have `webid` of the person and `client_id` of the application.

For Social Agent we often want to further disambiguate between Person and Organization. I would propose that we define Social Agent first and later we deal with further distinction.

ACP includes concept of [Pod Owner](https://github.com/solid/authorization-panel/blob/master/proposals/acp/definitions.md#pod-owner) to my understanding it would always be a Social Agent and never an Application.

I also think we should assume that an Application always acts on behalf of some Social Agent. That Social Agent delegates some access rights to the Application. Social Agent can either manually control the application or automate it some way that doesn't require them to manually control it. This Automation could range from simple static configuration to employing AIs.

Possibly we should explore some possible edge cases around Services but I believe we still should be able to draw distinction here between Social Agents and Applications. Service would be always provided by a Social Agent and any legal agreements would be between the Social Agents - provider and consumer of the service.

**Comment by elf-pavlik** [comment]
we could also consider adoption some of the terminology from GNAP ( Grant Negotiation and Authorization Protocol)

https://www.ietf.org/archive/id/draft-ietf-gnap-core-protocol-00.html#name-roles

> Resource Client (RC, aka "client")
>    Requests tokens from the AS and uses tokens at the RS. An instance of the RC software is identified by its key, which can be known to the AS prior to the first request. The AS determines which policies apply to a given RC, including what it can request and on whose behalf.

> Requesting Party (RQ, aka "user")
>    Operates and interacts with the RC.

**Comment by elf-pavlik** [comment]
> ACP includes concept of Pod Owner to my understanding it would always be a Social Agent and never an Application.

I think we could specify that Application (Software Agent)
* can not own data
* can not create access grants

**Comment by justinwb** [comment]
> Agree on terminology to distinguish software agent from social agent

+1 (also noting there was no disagreement on this in the panel session of 8/31)

Consequently, I think we need to settle some key open questions on how we describe a social agent vs. a software agent; what is the same about them and what is different?

Lets start with definitions, and then move to data model...

From the [Agent](https://solid.github.io/data-interoperability-panel/specification/#datamodel-agent) definition in the interoperability spec:

> An **Agent** is a distinct individual, group, organization, or piece of software with an identity that can be strongly authenticated.

I believe that this definition is still accurate as a blanket definition for both social agents (e.g. people, orgs) and software agents (e.g. bots). Looking at Social Agents and Software agents as derivatives, we could consider the following definitions:

A **Social Agent** is a strongly identifiable individual, group, or organization that can own or be responsible for data, and provide consent to the access of that data by other [Agents](https://solid.github.io/data-interoperability-panel/specification/#datamodel-agent) or [Applications](https://solid.github.io/data-interoperability-panel/specification/#datamodel-application).

A **Software Agent** is a strongly identifiable running instance of a software [Application](https://solid.github.io/data-interoperability-panel/specification/#datamodel-application) with an associated [Social Agent](#) responsible for its behavior.

**Comment by elf-pavlik** [comment]
> I believe that this definition is still accurate as a blanket definition for both social agents (e.g. people, orgs) and software agents (e.g. bots). 

I think Software Agents also include Applications.


>  by other Agents or Applications.

If Application is also an Agent (which I think it is) we can remove it from here. I would just go with

*by other Agents*


> A Software Agent is a strongly identifiable running instance of a software Application with an associated Social Agent responsible for its behavior.

I think we also shouldn't mention Application here, since Authorization Agent is also a Software Agent.

I would just go with

*A Software Agent is a strongly identifiable running instance of a software*

*NOTE: We make assumption that for any Software Agent there is a Social Agent who controls it in some way, for example using GUI, CLI, API, configuration files etc.*

BTW I noticed [GNAP - Termonology](https://www.ietf.org/archive/id/draft-ietf-gnap-core-protocol-06.html#section-1.1) has slightly changed.

> **Client** - application operated by an end-user that consumes resources from one or several RSs, possibly requiring access privileges from one or several ASs.
Example: a client can be a mobile application, a web application, etc.
Note: this specification differentiates between a specific instance (the client instance, identified by its unique key) and the software running the instance (the client software). For some kinds of client software, there could be many instances of that software, each instance with a different key.

We might want to base our definitions on *client instance* and *client software*

**Comment by justinwb** [comment]
> I think Software Agents also include Applications.

+1 - Agree with this

> If Application is also an Agent (which I think it is) we can remove it from here.

I agree with removing "or Applications" given the first point, but I'm not sure that we should consider an Application to be an Agent. I've always thought of the Application as something that is used by either a Social Agent or a Software Agent. 

> We might want to base our definitions on _client instance_ and _client software_

I think generally that's where we're landing with Software Agent (client instance), and Application (client software).

Adjusted Definitions:

A **Social Agent** is a strongly identifiable individual, group, or organization that can own or be responsible for data, and provide consent to the access of that data by other [Agents](https://solid.github.io/data-interoperability-panel/specification/#datamodel-agent).

A **Software Agent** is a strongly identifiable running instance of software

**Comment by elf-pavlik** [comment]
> but I'm not sure that we should consider an Application to be an Agent.

I guess Application in a pretty overloaded term. I usually think of an Application as OAuth Client - Client Instance in GNAP. If we would like to store Application Registrations and SocialAgent Registrations in Agent Registry it seems to make sense that both are considered Agents.

BTW another overloaded term came to my mind - *Peer*. We could define 'social agents' as Peers, and possibly just have *Application* and *Peer* as sub classes of *Agent*.

BTW since we make designation to AuthorizationAgent via *hasAuthorizationAgent*, it doesn't see to ever act as an Application (definitely not a Peer).

**Comment by justinwb** [comment]
Proposed definitions following the live discussion on 9/1:

A **Social Agent** is a strongly identifiable individual, group, or organization that can own or be responsible for data, and provide consent to the access of that data by other _Social Agents_ or _Client Applications_.

A **Client Application** is a piece of software that a _Social Agent_ uses to access, manipulate, and manage the data in their control, as well as the data they’ve been granted access to.

**Comment by elf-pavlik** [comment]
SGTM ✅

**Comment by justinwb** [comment]
@elf-pavlik I believe this was resolved by #169 (though I forgot to link it to the PR). Can you confirm and close if you agree?
