### ISSUE TITLE
consider alternatives for app registration discovery

### ISSUE THREAD

**Issue by elf-pavlik** [solid/data-interoperability-panel#91]
I think we can still improve how app discoveries its registration. First simple adjustment would be to publish an URI Template that app can discover.

Another approach would be that after consent from the user, the app is being provided with IRI of its registration. If app looses that information it just tries to register again and agent which would present consent screen can skips that step and again just provides existing registration reference to the app.

**Comment by elf-pavlik** [comment]
I'm thinking about ways for app to ask about location of their registration. Authorization Agent could respond to authenticated request from an app with location of their Application Registration in HTTP Link header.

**Comment by elf-pavlik** [comment]
I'm going to implement HTTP Link header approach, so:

1. Check user's WebID Document for statement with `interop:trustedAuthorizationAgent`
2. Send authenticated request to IRI in object position and check HTTP Link header with relation `http://www.w3.org/ns/solid/interop#requesterApplicationRegistration`

I find it simpler and more straight forward than rummaging through registry sets using hash of application identity.

We should also follow up on #98 since possibly only Authorization Agent will need a 'total entry point' and it has trusted agent status.

**Comment by elf-pavlik** [comment]
Actually we could even reuse terms used for `ApplicationRegistration` in [example from Primer](file:///Users/elf-pavlik/code/solid/data-interoperability-panel/proposals/primer/index.html#application-registration) we find:

```turtle
alice-auth:bcf22534-0187-4ae4-b88f-fe0f9fa96659
  a interop:ApplicationRegistration ;
    # [...]
    interop:registeredApplication <https://projectron.example/#app> .
```

Application after discovering user's authorization agent could make simple authenticated HEAD request end expect to find in response:

```http
Link: <https://projectron.example/#app>;
      rel="http://www.w3.org/ns/solid/interop#registeredApplication";
      anchor="https://auth.alice.example/bcf22534-0187-4ae4-b88f-fe0f9fa96659"
``` 

Based on that application making authenticated request knows location of its Application Registration.

**Comment by justinwb** [comment]
This is a nice approach - certainly much better / lighter weight for client implementations. I *believe* there may still be a benefit to having a low-tech option, but I could see this being the favored approach and maybe the right way long-term.

**Comment by elf-pavlik** [comment]
I implemented mentioned HTTP Link header mechanism in sai-js

**Comment by elf-pavlik** [comment]
If we only specify approach based on HTTP Link header https://github.com/solid/data-interoperability-panel/issues/76 will become irrelevant.

**Comment by elf-pavlik** [comment]
I think we should just continue in #291
